#!/bin/sh

# shellcheck source=scripts/core/sxmo_common.sh
. hyprmo_common.sh

# Please modify this file to your liking

# Important Instructions:
#  All processes you launch from this script must
#  be non-blocking: launch them in the background (using &)
#  or ensure they return quickly. Only after this script
#  finishes will the window manager be loaded

# You will sometime get SMS or calls from not
#  country code prefixed phone numbers. To make
#  it easy to fixup configure the default countryu.
#export DEFAULT_COUNTRY=FR

### Configuration Parameters ###

# Note that this is just a subset of all available
# parameters, see the hyprmo documentation for more.

# Use firefox as default browser if installed
command -v firefox >/dev/null && export BROWSER=firefox

# Prepopulate Subreddits menu with custom subreddits
#export HYPRMO_SUBREDDITS="postmarketos pinephoneOfficial pinephone unixporn"

# Change the default terminal command
export TERMCMD="hyprmo_terminal.sh"

# Change the used terminal command
# export HYPRMO_TERMINAL="st"

# When scrolling past the beginning or end of a menu, wrap it around:
#export DMENU_WRAP_AROUND=1

# Enable audio feedback on keypress
#export KEYBOARD_ARGS="-o | clickclack -f $(xdg_data_path sxmo/keytap.wav)"

# Or, enable vibration feedback on keypress
#export KEYBOARD_ARGS="-o | clickclack -V"

# Set the scale factor in Hyprland
export HYPR_SCALE=2

# Set the rotation for Hyprland. 
# 0 = 0° (Portrait)
# 1 = 90° (Landscape-Right)
# 2 = 180° (Reversed Portrait)
# 3 = 270° (Landscape-Left PPKB)  
export HYPR_TRANSFORM=0

# Set Monitor configuration for Hyprland
export HYPR_MONITOR_CONFIG=,preferred,auto,$HYPR_SCALE,transform,$HYPR_TRANSFORM

# To load specific part of configuration depending on the running environment
case "$HYPRMO_WM" in
	hyprland)
		;;
esac

#Set RINGTONE to audio file to play for incoming call
export HYPRMO_RINGTONE="$(xdg_data_path hyprmo/ring.ogg)"

#Set TEXTSOUND to audio file to play when received text message
export HYPRMO_TEXTSOUND="$(xdg_data_path hyprmo/notify.ogg)"

#Set RINGTIME to number of seconds the phone will ring
export HYPRMO_RINGTIME=20

#Set RINGNUMBER to number of times phone will ring or repeat ringtone
#(whichever of HYPRMO_RINGTIME or HYPRMO_RINGNUMBER runs less will limit how long phone rings)
export HYPRMO_RINGNUMBER=10

#Set to the default text for a new text message.
export HYPRMO_DEFAULT_DRAFT="Enter new message here."

#Set background image
#export HYPRMO_BG_IMG="$(hyprmo_hook_wallpaper.sh)"
